version: '3.3'
services:
    exercise-0.0.1-SNAPSHOT:
      build: ./
      image: exercise-0.0.1-SNAPSHOT:1.0
      restart: always
      container_name: exercise-0.0.1-SNAPSHOT
      ports:
        - 8299:8299
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
      network_mode: bridge